### PR TITLE
Fixes #88. Not showing the dimensions editor if we still don't have the template from the new active layer (since committing to the template the new layer might take longer).

### LINKED ISSUE #88: Layer Copying not updating edit forms correctly
**Describe the bug**
from `@greema` via Discord:
> when copying a layer, the new layer is high-lited, so you think you are working in the newly created layer, but you are actually still in the original layer

Investigate and fix.

### PR DESCRIPTION
**Pull request by riverole**
Not showing the dimensions editor if we still don't have the template from the new active layer (since committing to the template the new layer might take longer).

### CODE REVIEW

File: lib/components/template/layer/ImageLayerEditor.vue [hunk 1]
```diff
@@ -93,7 +93,8 @@ v-expansion-panel#image-layer-editor(popout)
       dimensions() { return this.getLayerDimensions(this.layer) },
 
       templateSize() {
-        return this.findTemplateByLayerId(this.layer.id).size
+        let template = this.findTemplateByLayerId(this.layer.id)
```
Comment (lorennorman) [inline lib/components/template/layer/ImageLayerEditor.vue:96]: use `const` when you aren't overwriting the variable

File: lib/components/template/layer/ImageLayerEditor.vue [hunk 2]
```diff
@@ -93,7 +93,8 @@ v-expansion-panel#image-layer-editor(popout)
...
+        return template ? template.size : template
```
Comment (lorennorman) [inline lib/components/template/layer/ImageLayerEditor.vue:97]: `return template && template.size`

Comment (lorennorman) [reply lib/components/template/layer/ImageLayerEditor.vue:97]: and after release when we update everything, i'll enable the "null soaking" operator so we can just do:
`return template?.size`

File: lib/components/template/layer/ImageLayerEditor.vue (hunk 1 above)
Comment (riverole) [reply lib/components/template/layer/ImageLayerEditor.vue]: Done

File: lib/components/template/layer/ImageLayerEditor.vue (hunk 2 above)
Comment (riverole) [reply lib/components/template/layer/ImageLayerEditor.vue]: Done!
