### PR TITLE
Ensuring to load spreadsheet for each component in a game after mounting the component card. This ensures the numbers are correct for the component cards. Fixes #4

### LINKED ISSUE #4: Components are not showing the number of cards after clicking edit in a game
**Describe the bug**
Components are not showing the number of cards after clicking edit in a game. They will only show after I click on one of the components (at that point for both components it shows the number of cards and other info).

**To Reproduce**
1. Create a new game.
2. Create new components, with multiple cards each for the game.
3. Log out paperize.
4. Log in and click edit in your game.

**Expected behavior**
The components should show the number of cards that you already have, etc.

**Screenshots**
After clicking edit in the game, it shows no cards:
NoCardsForComponent
After selecting one of the components, they load:
CardsForComponent

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Browser: Chrome
 - Paperize Version: ver.A7.0.1

### PR DESCRIPTION
**Pull request by riverole**
Ensuring to load spreadsheet for each component in a game after mounting the component card. This ensures the numbers are correct for the component cards

### CODE REVIEW

**Comment by lorennorman** [comment]
Fixes #4 (just trying to get GitHub to trigger the connection between PR and Issue)

File: lib/components/component/ComponentCard.vue [hunk 1]
```diff
@@ -27,6 +27,12 @@ v-flex.component(sm10 :elevation-10="isActiveComponent()" :class="{ active: isAc
       }
     },
 
+    mounted() {
+      if(this.component.spreadsheetId) {
+        this.ensureSheetIndexed(this.component.spreadsheetId)
```
Comment (lorennorman) [inline lib/components/component/ComponentCard.vue]: Great work tying into the Vue component lifecycle, and finding a pre-existing Vuex action that did what you needed!
