### PR TITLE
Avoid printing empty pages for components without rows or components without any layers in it. Fixes #19.

### LINKED ISSUE #19: Components with no Items still generate a blank page
**Describe the bug**
A component with no items still generates a blank page.

**To Reproduce**
1. Create a component, add printable items to it
2. Create a component, but don't add anything to its sheet
2. Print the game
3. Observe an empty page at the end from the empty component

**Expected behavior**
There should be no empty page at all, Paperize is adding a page to the document before it checks how many items it will put on it.

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Browser: Chrome

**Additional Context:**
Most likely change is in `pdf_renderer/layout.js`:
https://github.com/paperize/paperize/blob/d2b9d14470efced3310283d151fc827b742e7e69/lib/services/pdf_renderer/layout.js

### PR DESCRIPTION
**Pull request by riverole**
Avoid printing empty pages for components without rows or components without any layers in it. Fixes #19 .

### CODE REVIEW

File: lib/services/pdf_renderer/index.js [hunk 1]
```diff
@@ -24,9 +24,8 @@ const publicApi = {
   renderGameToPdf(game) {
     store.dispatch("startNewPrintJob")
 
-    const components = store.getters.findAllGameComponents(game),
+    const components = store.getters.findAllPrintableGameComponents(game),
```
Comment (lorennorman) [inline lib/services/pdf_renderer/index.js]: Nice work!
- an intention-revealing getter name
- part of the intention removes the null check 2 lines later

One extra thing that can now be removed is the `compact` call, which catches and removes those nulls that we're no longer returning.

File: lib/store/games.js [hunk 2]
```diff
@@ -32,6 +32,18 @@ const GameModel = {
       return rootGetters.findAllComponents(game.componentIds)
     },
 
+    findAllPrintableGameComponents: (_, __, ___, rootGetters) => game => {
+      return rootGetters.findAllComponents(game.componentIds).filter(c => {
```
Comment (lorennorman) [inline lib/store/games.js]: Here's something I try to stick to: full word variable names, no abbreviations or initials. They just get impossible to work with as the codebase grows, so I take the hit early to keep my code overly readable.

Comment (lorennorman) [reply lib/store/games.js]: Another thing here is the use of `findAll` and then a `filter`, I'm thinking that we've already got some power in a `search*` method or something from my CRUD resource scaffolding. I'm going to poke around and try to find a tighter way to do this getter...
